name: Deploy static content to Pages

on:
  push:
    branches: ["main"]  # 触发条件：当推送到 main 分支时

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境
    permissions:
      pages: write       # 授予 Pages 权限
      id-token: write    # 授予写入 ID Token 的权限
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # 设置环境变量，包含部署后的页面 URL
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2  # 使用 actions/checkout@v2 动作来检出代码

      - name: Setup Pages
        uses: actions/configure-pages@v1  # 设置 GitHub Pages 环境
        with:
          static_site_generator: false  # 因为是静态内容，不使用静态站点生成器
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1  # 上传页面工件
        with:
          path: '.'  # 上传当前目录下的所有文件（你的静态内容）

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1  # 部署到 GitHub Pages
